### ISSUE TITLE
which loader.config to use

### ISSUE THREAD

**Issue by ramotswa** [AstunTechnology/Loader#29]
Hi,
I'm trying to load some addressbase premium. so I've seen the 'extras' folder which contains addressbase premium stuff, including sql view creation scripts. I presume these need to be run first? before doing the loader.py? 
then in the pgdump folder (in /extras/ordnancesurvey/addressbase/premium/) there is another loader.config table and also some create-index and table .sql files.. bit confused as to what exactly to use to load addressbase premium.

so far I have run the create-table.sql and create-index.sql and am starting to edit the loader.config file but just wanted to double check. 

Also, the loader.config file in /extras/ordnancesurvey/addressbase/premium/pgdump was missing (the quite informative) lines;

```
#   $output_dir - the directory specified by the out_dir setting
#   $base_file_name - the file name of the file to be loaded
#   $file_path - the full path of the file to be loaded
```

**Comment by walkermatt** [comment]
@ramotswa all of the config files in the repo are examples. Have you seen the following: https://github.com/AstunTechnology/Loader/wiki/Configuration-examples#addressbase-premium-to-postgresqlpostgis?

The AddressBase Premium content under `extras/ordnancesurvey/addressbase/premium/pgdump` is for bulk loading via PGDump and requires that you create the tables prior to load and indexes after.

You only really need to use PGDump format when you are loading a large quantity of data. Otherwise you can use the PostgreSQL driver the `ogr_cmd` as shown in the [default loader.config](https://github.com/AstunTechnology/Loader/blob/master/python/loader.config#L28)

**Comment by walkermatt** [comment]
@ramotswa just wondering if this can now be closed?

**Comment by ramotswa** [comment]
hi @walkermatt - yes sorry. Although I didn't manage to get it working I don't think it's a problem on your side.. more user error. Thanks for the pointers.
